### ISSUE TITLE
Missing RadioDNS at Rock Radio Slovenia

### ISSUE THREAD

**Issue by andimik** [KejPi/AbracaDABra#103]
Althought the console says,

```
19:10:21.969 [W] SPIApp: DNS lookup failed: "0.9516.9200.9e4.dab.radiodns.org"
```

there are files in the `.cache/AbracaDABra/` folder containing the RadioDNS logos for Rock Radio Slovenia.

But the do not appear in the Window.

![32x32](https://github.com/KejPi/AbracaDABra/assets/24510556/0c5d629f-8cc6-4720-8aa2-a044376431dc)
![320x240](https://github.com/KejPi/AbracaDABra/assets/24510556/f26f5ad8-a867-4dde-a7a1-6cf8052abd27)

![grafik](https://github.com/KejPi/AbracaDABra/assets/24510556/4e169f75-2853-4489-a00c-e0fdb40c74b0)

For all other stations it works.

![grafik](https://github.com/KejPi/AbracaDABra/assets/24510556/84cf179f-b480-4b96-9e43-651105e3833d)

But Radio Center does not have SPI logos in the multiplex.

So I fear RadioDNS and SPI are mixed up in your application.

```
19:12:46.757 [I] RadioControl: Found user application type 'SPI' within ensemble in data service SId E4910001, SCIdS 0. Starting the service...
```

**Comment by KejPi** [comment]
What is the directory where you have found Radio rock logos? 
What do you mean by mixed? Application does not distinguish where the logo comes from. If the logo exists in the cache it is shown.

**Comment by andimik** [comment]
No

**Comment by KejPi** [comment]
What do you mean?

**Comment by andimik** [comment]
> If the logo exists in the cache it is shown.

No. See above. The cache has these two files, but it is not shown.

**Comment by KejPi** [comment]
What is the directory where you have found Radio rock logos?

**Comment by KejPi** [comment]
Application does not store XML files anywhere to avoid filling disk with data that is not needed to be persistent. Logos are stored in cache in directory name created from combination of ECC+SId+SCId that shall be unique worldwide (SCId might be removed in future). When service is selected, application checks if logos exist in that direcory and it yes, it is showing them.

**Comment by KejPi** [comment]
I have check the situation with recording kindly shared by @bostjane in Issue #90 and unless anything changed the behavior of application is aligned with the expectations. 

Rock Radio does not have logo in SPI MOT directory, neither provided by its own RadioDNS service. But it is included in SI file for Center Slo service. The bearer defined in that SI.xml file for Rock Radio is this:

`<bearer id="dab:9e4.9200.9416.0" cost="1" mimeValue="audio/aacp" offset="1000"/>`

It means ECC 0xE4 and SId 0x9416, SCIdS = 0, in other words the logos shall be stored in <CACHE>/e49416.0 directory where they really are at least in my case replaying the recording.

The problem is, that SId of Rock Radio in 0x9200 is 0xE49516:

`[E49200 @ 174928 kHz |  5A] Rock Radio Slo     E49516 : 0`

This is the reason why logo is not displayed.

SI.xml is here: `wget http://tcp.radiocenter.si/radiodns/spi/3.1/SI.xml`

This is bug in configuration in my opinion, the broadcaster should match bearer item with DAB source.

**Comment by andimik** [comment]
OK thanks, maybe I will report it to the broadcaster or to the operator.
