### ISSUE TITLE
MOT directory parsing failed

### ISSUE THREAD

**Issue by andimik** [KejPi/AbracaDABra#112]
Since this week, the second national muxes (R2 West and R2 East) in Slovenia have an SPI service, but - other than for my other ensembles here in Southern Austria - no files are written to `~/.cache/AbracaDABra`

The message on the console is this all the time:

```
MOT directory parsing failed
```

[slo_12c_short.zip](https://github.com/KejPi/AbracaDABra/files/13999130/slo_12c_short.zip)

But there are several logo pictures in the SPI, as I could extract them with Qt-DAB, for example

![10120](https://github.com/KejPi/AbracaDABra/assets/24510556/cff36cd9-f8df-4f64-af90-3a5e644da303)

![28171](https://github.com/KejPi/AbracaDABra/assets/24510556/cb952b0b-17e2-4dd3-b1ff-9fd062b7402a)

![65140](https://github.com/KejPi/AbracaDABra/assets/24510556/d9a5c28a-92b4-4d82-b81d-f813c2a91f33)

**Comment by KejPi** [comment]
Thank you for reporting and for sharing the recording. It is actually very interesting because in this recording FEC scheme is not signalled (FIG 0/14) and actually seems really not to be used. It should not be the case on air today however still permitted by standard.  
I have analysed what is going on and I have found an embarrassing bug - I am surprised it did not appear sooner.

**Comment by andimik** [comment]
ah, cool fix :-)

Well, it seems the SPI service is still under construction by the broadcaster as it only contains files for one program ...
