### ISSUE TITLE
Android version

### ISSUE THREAD

**Issue by Nico239SF** [KejPi/AbracaDABra#132]
Will you ever develop a version of this app for android? This software is way better than welle.io, and lighter.

**Comment by KejPi** [comment]
Currently I have no plans for that because I have no bandwidth to work on additional OS (even support for Ubuntu needs significantly more time compared to other OS) and I also have no experience with Android development and no Android HW for testing it. It would also require major UI redesign since existing UI is not suitable for touch screen.
