### ISSUE TITLE
Wrong service shown than selected shown when scrolling too fast

### ISSUE THREAD

**Issue by andimik** [KejPi/AbracaDABra#142]
This issue is similar to one we had in the very early days. It seems to be a timing problem.

When scrolling the list through very fast (here: with arrow down), it may happen, that the selected service is not that one which is shown.

![grafik](https://github.com/KejPi/AbracaDABra/assets/24510556/4b6d20cc-f256-411f-9f4b-0d9e18eaecff)

Here you see a mixture of 3 different Radio stations from 2 muxes. 

You can see that in the video

[Bildschirmaufzeichnung vom 08.06.2024, 15:27:39.webm](https://github.com/KejPi/AbracaDABra/assets/24510556/5d53472d-a43d-4c2d-92a1-6546ae5817c6)

**Comment by KejPi** [comment]
Please check if this issue can be still reproduced with last build.

**Comment by andimik** [comment]
No, not fixed.

![grafik](https://github.com/KejPi/AbracaDABra/assets/24510556/60fca131-30f9-4bcf-b77b-486739ee67cf)

**Comment by KejPi** [comment]
I do not know how to reproduce it. I have fixed what I could reproduce a since then it is no longer happening on my machine 🙁

**Comment by andimik** [comment]
Is there a caching problem with SPI or RadioDNS?

Because the service name now is the right one.

And it seems that there is a check in between as there is a short break and only then the display refreshes.

**Comment by KejPi** [comment]
The problem happens when there is a tune to new ensemble, I was not able to reproduce any problem while scrolling in the services from one ensemble.
So in the screenshot Fantasi is selected in the tree, it is indicated by service name, it is playing but the logos belong to VAL 202, correct?
Are the logos displayed as expected when you select the service by "normal" clicking? Actually, are there any logos available for Fantasi service? If not, maybe it could be the reason to be checked.

**Comment by andimik** [comment]
[Bildschirmaufzeichnung vom 17.06.2024, 07:19:56.webm](https://github.com/KejPi/AbracaDABra/assets/24510556/f0b92b40-8d39-46f7-858b-18942f1dcb33)

Yes, this solved it.
