### ISSUE TITLE
Transparent PNG background color

### ISSUE THREAD

**Issue by andimik** [KejPi/AbracaDABra#144]
Do you have an idea how to prevent this behavior with transparent PNG files in **SPI**?

![Bildschirmfoto vom 2024-07-02 23-36-33](https://github.com/KejPi/AbracaDABra/assets/24510556/6b5a4c60-6a34-4826-abf9-c37a57c438ae)
![e0_ad68_320x240_3](https://github.com/KejPi/AbracaDABra/assets/24510556/d1267b69-a577-44b7-af90-03cef9e56e4c)
![e0_ad68_128x128_2](https://github.com/KejPi/AbracaDABra/assets/24510556/695cea02-2022-453c-99e4-9f142b05c40e)
![e0_ad68_112x32_1](https://github.com/KejPi/AbracaDABra/assets/24510556/6b27d5b3-65b9-42c3-a265-92d533e3ea6b)
![e0_ad68_32x32_0](https://github.com/KejPi/AbracaDABra/assets/24510556/88f7bd38-aa84-4b63-be90-59bf7f8be705)

When **SLS** has been received, then the file is a JPG.
![Bildschirmfoto vom 2024-07-02 23-37-18](https://github.com/KejPi/AbracaDABra/assets/24510556/8104c8b2-9da2-4b68-a836-6f52cb7ab49a)

![sls1_6](https://github.com/KejPi/AbracaDABra/assets/24510556/2992f63c-a7c1-4df7-899a-43507e17921e)

**Comment by KejPi** [comment]
Well, it is black because all slides have black background that is not visible for non-transparent images but it appears when image is smaller or if it has transparency. I was looking for some guidelines in documentation from WorldDAB and I have not found any recommendation what to do with transparent logos. When I was implementing it, my assumption was that typical car radio has a black screen and dark UI. So I would assume broadcasters should provide their media assets in the format that looks good in car because it is the majority of radio listening. The other assumption that shall be considered is that in dark mode the image background should be dark too. 
To be honest, I do not have any reference how the manufacturers are implementing station logos visualization for DAB, if you have any, please share.

**Comment by andimik** [comment]
But the smaller file (top left) is visible, although it is transparent (see files below), too!

So you should use the same background color in the SLS window.

**Comment by KejPi** [comment]
Yes, it is visible because I do not set any background there, but try how visible it is in dark mode.

**Comment by KejPi** [comment]
This is probably the best compromise. By the way - you can see how stupid they are :-D This is clearly problem on their side,  if they want to have white background they should set it in the logo or make the logo in the way that looks good on any background color in gray scale.

<img width="889" alt="Snímek obrazovky 2024-07-04 v 20 53 10" src="https://github.com/KejPi/AbracaDABra/assets/6438380/317ed6ef-388b-4a74-9b7a-9c1154af7766">

**Comment by andimik** [comment]
BTW: have a look at the letter `R` ...

**Comment by KejPi** [comment]
Yes, this is what I meant when calling them stupid. It is also in A letter.

**Comment by andimik** [comment]
I just saw that the transparent logos look good in the EPG window, as your background color is the same grey.

![grafik](https://github.com/user-attachments/assets/70c31cae-6058-4ff4-b250-f248fe75e11d)

![32x32](https://github.com/user-attachments/assets/f99f069c-4c7b-4251-9c4b-2c2e493d4094)
![32x32](https://github.com/user-attachments/assets/d06a25c0-02ec-44a9-b2e0-3126c9d5d435)

**Comment by KejPi** [comment]
Try to change to dark mode ;-)

**Comment by KejPi** [comment]
@andimik What about this? 
I could implement a possibility to set slideshow background from settings dialog. Would it resolve this issue?

**Comment by KejPi** [comment]
User can select any SLS background in settings, closing issue.
