### ISSUE TITLE
Show real service during Alarm and Alarm test 

### ISSUE THREAD

**Issue by andimik** [KejPi/AbracaDABra#92]
I've realized that during an active Alarm or Alarm test announcement the audio switches to that service, but you cannot see it in the window. The only index is the bitrate and protection level, which is **not** that from the displayed service, but from the announcement service.

In this window I expect switching to the following SubCh 

```
15:35:06.803 [I] RadioControl: "Alarm Test" announcement in subchannel 10 cluster ID 254
```

![grafik](https://github.com/KejPi/AbracaDABra/assets/24510556/2e04c525-ae7d-48ca-96e1-4c903a9c5a49)

**Comment by KejPi** [comment]
Showing the original service name is done by purpose and it is expected behavior of the receiver. If technical info about bitrate etc. does not match Radio Horeb it is probably a bug and I will fix it. It woudl be helpful if you could share the recording for testing. 
PS: some infomation about source of the announcement is in tooltip of the announcement icon.

**Comment by KejPi** [comment]
What about this? Parameters are in disabled state but showing original service information during announcement from other service. 

<img width="890" alt="Snímek obrazovky 2023-10-25 v 19 52 05" src="https://github.com/KejPi/AbracaDABra/assets/6438380/55ccc41d-ee4f-4aa8-9740-a3d57dd580e9">

**Comment by andimik** [comment]
I realized that there is a tool tip saying the service. I guess it can be closed.

Tested with 🇩🇪 Munich 10D (other 📢 announcements)
